/* =================== provisional course quizzes ===================
   Written from each course's title and the usual syllabus for it, NOT from
   real course material — none exists yet. Every course carrying one of these
   sets is flagged provisional, and says so on entry.

   Text is {sv, en}; L() picks the active language. Plain strings are returned
   unchanged, which is how the older English-only material keeps working.

   When the real syllabus arrives: replace the set here and drop `provisional`
   in vm-courses.js. */
const COURSE_QUIZZES = {

natverkssakerhet: [
{tier:{sv:"Segmentering och kontroll", en:"Segmentation and control"}, items:[

{q:{sv:"Varför delar man upp ett nätverk i segment?",
    en:"What is the point of splitting a network into segments?"},
 o:[{t:{sv:"En angripare som tar sig in i ett segment når inte automatiskt de andra",
        en:"An intruder who lands in one segment cannot automatically reach the others"},c:1},
    {t:{sv:"Trafik som aldrig passerar en gräns kan inte angripas vid den gränsen",
        en:"Traffic that never crosses a boundary cannot be attacked at that boundary"},c:1},
    {t:{sv:"Nätverket blir alltid snabbare", en:"It makes the network faster in every case"}},
    {t:{sv:"Regler kan skrivas per segment i stället för per värd",
        en:"Rules can be written per segment rather than per host"},c:1}],
 e:{sv:"Segmentering begränsar <b>lateral rörelse</b>. Utgå från att något blir komprometterat — frågan är hur långt det når. Hastighet är i bästa fall en bieffekt.",
    en:"Segmentation limits <b>lateral movement</b>. Assume something will be compromised; the question is how far it gets. Speed is a side effect at best."}},

{q:{sv:"Vad är en DMZ?", en:"What is a DMZ?"},
 o:[{t:{sv:"Ett segment för tjänster som måste nås från internet, isolerat från det interna nätet",
        en:"A segment for services that must be reachable from the internet, isolated from the internal network"},c:1},
    {t:{sv:"Ett nät helt utan brandvägg", en:"A network with no firewall at all"}},
    {t:{sv:"Den del av nätet där ingen loggning sker", en:"The part of the network where no logging happens"}},
    {t:{sv:"Ett segment som nås utifrån men själv inte får öppna förbindelser inåt",
        en:"A segment reachable from outside that cannot itself open connections inward"},c:1}],
 e:{sv:"En DMZ rymmer det omvärlden måste nå — en webbserver, en mailrelä — så att ett intrång där inte lämnar över det interna nätet. Trafik inåt begränsas, inte tvärtom.",
    en:"A DMZ holds what the outside must reach — a web server, a mail relay — so that compromising it does not hand over the internal network. Traffic inward is restricted, not the other way round."}},

{q:{sv:"Varför är default-deny normalläget i en brandvägg?",
    en:"Why is default-deny the normal stance on a firewall?"},
 o:[{t:{sv:"Du behöver bara resonera om det du medvetet öppnat",
        en:"You only have to reason about what you deliberately opened"},c:1},
    {t:{sv:"Allt nytt blockeras tills någon beslutar annat",
        en:"Anything new is blocked until someone decides otherwise"},c:1},
    {t:{sv:"Det tar bort behovet av loggning", en:"It removes the need for logging"}},
    {t:{sv:"Default-allow kräver att man räknar upp varje tänkbart angrepp, vilket är omöjligt",
        en:"Default-allow means enumerating every possible attack, which is impossible"},c:1}],
 e:{sv:"Med default-allow försöker du lista allt farligt, vilket aldrig tar slut. Med default-deny listar du det som behövs, vilket är ändligt och går att granska.",
    en:"With default-allow you are trying to list everything bad, which never ends. With default-deny you list what is needed, which is finite and reviewable."}},

{q:{sv:"Vad skiljer en tillståndslös från en tillståndsbaserad brandvägg?",
    en:"What is the difference between a stateless and a stateful firewall?"},
 o:[{t:{sv:"Den tillståndsbaserade följer förbindelser, så svar på tillåten trafik släpps igenom automatiskt",
        en:"A stateful firewall tracks connections, so replies to a permitted request are allowed automatically"},c:1},
    {t:{sv:"Den tillståndslösa bedömer varje paket för sig",
        en:"A stateless firewall judges each packet on its own"},c:1},
    {t:{sv:"Tillståndslösa brandväggar är säkrare av konstruktion",
        en:"Stateless firewalls are more secure by design"}},
    {t:{sv:"Tillståndsbaserade kan inte filtrera på port",
        en:"Stateful firewalls cannot filter by port"}}],
 e:{sv:"Utan tillståndsspårning måste du öppna båda riktningarna för hand, vilket nästan alltid blir alldeles för tillåtande.",
    en:"Stateless filtering means opening both directions by hand, which usually ends up far too permissive. Connection tracking is what makes a tight ruleset practical."}}]},

{tier:{sv:"Skydda trafiken", en:"Protecting the traffic"}, items:[

{q:{sv:"Vad ger TLS dig egentligen?", en:"What does TLS actually give you?"},
 o:[{t:{sv:"Sekretess — en avlyssnare kan inte läsa trafiken",
        en:"Confidentiality — an observer cannot read the traffic"},c:1},
    {t:{sv:"Integritet — manipulation upptäcks", en:"Integrity — tampering is detected"},c:1},
    {t:{sv:"Autentisering av servern, via dess certifikat",
        en:"Authentication of the server, via its certificate"},c:1},
    {t:{sv:"En garanti för att servern inte är illasinnad",
        en:"A guarantee that the server is not malicious"}}],
 e:{sv:"TLS visar att du talar med innehavaren av certifikatet, oläst och oförändrat. Det säger ingenting om huruvida den parten förtjänar förtroende — en nätfiskesajt kan ha ett fullt giltigt certifikat.",
    en:"TLS proves you are talking to the holder of that certificate, unmodified and unread. It says nothing about whether that party deserves trust — a phishing site can hold a perfectly valid certificate."}},

{q:{sv:"Vad skiljer IDS från IPS?", en:"What is the difference between an IDS and an IPS?"},
 o:[{t:{sv:"IDS upptäcker och larmar; IPS sitter i trafikvägen och kan blockera",
        en:"An IDS detects and alerts; an IPS sits in the path and can block"},c:1},
    {t:{sv:"IPS kan släppa trafik, så en falsk positiv orsakar avbrott",
        en:"An IPS can drop traffic, so a false positive causes an outage"},c:1},
    {t:{sv:"IDS är alltid snabbare", en:"An IDS is always faster"}},
    {t:{sv:"Det är två namn på samma sak", en:"They are two names for the same thing"}}],
 e:{sv:"Avvägningen är verklig: detektion är ofarlig men passiv, prevention är aktiv men en dålig regel tar ner produktionen. Därför körs IPS oftast i detektionsläge först.",
    en:"The trade is real: detection is safe but passive, prevention is active but a bad rule takes down production. That is why an IPS is usually run in detection mode first."}},

{q:{sv:"Hur fungerar ARP-spoofing, och vad stoppar det?",
    en:"How does ARP spoofing work, and what stops it?"},
 o:[{t:{sv:"Angriparen svarar på ARP-förfrågningar med sin egen MAC, så trafiken skickas dit",
        en:"The attacker answers ARP requests with their own MAC, so traffic is sent to them"},c:1},
    {t:{sv:"Det fungerar för att ARP saknar autentisering",
        en:"It works because ARP has no authentication"},c:1},
    {t:{sv:"Switchfunktioner som dynamic ARP inspection och port security begränsar det",
        en:"Switch features like dynamic ARP inspection and port security limit it"},c:1},
    {t:{sv:"HTTPS gör det omöjligt", en:"HTTPS makes it impossible"}}],
 e:{sv:"Kryptering begränsar skadan — angriparen ser chiffertext — men omdirigeringen sker ändå. Åtgärden hör hemma i lager 2, på switchen.",
    en:"Encryption limits the damage — the attacker sees ciphertext — but the redirection still happens. The fix belongs at layer 2, on the switch."}},

{q:{sv:"När är ett VPN rätt svar?", en:"When is a VPN the right answer?"},
 o:[{t:{sv:"När trafik ska bäras säkert över ett nät du inte kontrollerar",
        en:"Carrying traffic safely across a network you do not control"},c:1},
    {t:{sv:"För att ge distansarbetande åtkomst till interna system",
        en:"Giving remote staff access to internal systems"},c:1},
    {t:{sv:"Som skydd mot en komprometterad klient",
        en:"Protecting against a compromised endpoint"}},
    {t:{sv:"För att koppla ihop två kontor över internet",
        en:"Connecting two sites over the public internet"},c:1}],
 e:{sv:"Ett VPN säkrar vägen, inte ändpunkterna. En laptop med skadlig kod på ett VPN är en laptop med skadlig kod — med en tunnel rakt in i nätet.",
    en:"A VPN secures the path, not the ends. A malware-infected laptop on a VPN is a malware-infected laptop with a tunnel straight into your network."}}]}],

kryptering: [
{tier:{sv:"Kryptografins byggstenar", en:"The building blocks"}, items:[

{q:{sv:"Vad skiljer symmetrisk från asymmetrisk kryptering?",
    en:"What separates symmetric from asymmetric cryptography?"},
 o:[{t:{sv:"Symmetrisk använder en delad nyckel för både kryptering och dekryptering",
        en:"Symmetric uses one shared key for both encryption and decryption"},c:1},
    {t:{sv:"Asymmetrisk använder ett nyckelpar: det ena låser, det andra låser upp",
        en:"Asymmetric uses a key pair: what one key locks, the other unlocks"},c:1},
    {t:{sv:"Symmetrisk är betydligt snabbare och gör därför grovjobbet",
        en:"Symmetric is far faster, so it does the bulk work"},c:1},
    {t:{sv:"Asymmetrisk är alltid säkrare", en:"Asymmetric is always more secure"}}],
 e:{sv:"I praktiken kombineras de: asymmetrisk kryptering enas om en nyckel, symmetrisk krypterar sedan datan. Ingen är bättre — de löser olika problem.",
    en:"In practice they are combined: asymmetric crypto agrees on a key, symmetric crypto encrypts the data. Neither is better — they solve different problems."}},

{q:{sv:"Vad används hashning till, och hur skiljer det sig från kryptering?",
    en:"What is hashing for, and how does it differ from encryption?"},
 o:[{t:{sv:"En hash är enkelriktad — det finns ingen nyckel som vänder tillbaka den",
        en:"A hash is one-way — there is no key that turns it back"},c:1},
    {t:{sv:"Hashning verifierar integritet; kryptering skyddar sekretess",
        en:"Hashing verifies integrity; encryption protects confidentiality"},c:1},
    {t:{sv:"Hashning är kryptering med dold nyckel",
        en:"Hashing is just encryption with a hidden key"}},
    {t:{sv:"Samma indata ger alltid samma hash", en:"The same input always gives the same hash"},c:1}],
 e:{sv:"Talar någon om att «dekryptera en hash» har de missförstått. Man vänder inte en hash — man hashar en gissning och jämför.",
    en:"If someone talks about 'decrypting a hash', they have misunderstood it. You do not reverse a hash — you hash a guess and compare."}},

{q:{sv:"Varför saltas lösenord innan de hashas?", en:"Why are passwords salted before hashing?"},
 o:[{t:{sv:"Identiska lösenord ger olika hashar, så en knäckt avslöjar inte de andra",
        en:"Identical passwords produce different hashes, so one crack does not reveal others"},c:1},
    {t:{sv:"Förberäknade tabeller som rainbow tables slutar fungera",
        en:"Precomputed tables such as rainbow tables stop working"},c:1},
    {t:{sv:"Saltet måste hållas hemligt för att vara till nytta",
        en:"The salt must be kept secret to be useful"}},
    {t:{sv:"Varje gissning kostar angriparen mer arbete",
        en:"It makes each guess cost the attacker more work"},c:1}],
 e:{sv:"Ett salt är ingen hemlighet — det lagras bredvid hashen. Uppgiften är att göra varje lösenord till ett eget problem i stället för ett gemensamt.",
    en:"A salt is not a secret — it is stored right next to the hash. Its job is to make every password a separate problem instead of one shared one."}},

{q:{sv:"Vilka egenskaper bör en modern lösenordshash ha?",
    en:"Which properties should a modern password hash have?"},
 o:[{t:{sv:"Medvetet långsam, så att gissning blir dyrt",
        en:"Deliberately slow, so guessing is expensive"},c:1},
    {t:{sv:"Minneskrävande, så att GPU:er och ASIC:ar hjälper mindre",
        en:"Memory-hard, so GPUs and ASICs help less"},c:1},
    {t:{sv:"Så snabb som möjligt", en:"As fast as possible"}},
    {t:{sv:"En funktion byggd för ändamålet, som Argon2 eller bcrypt, inte SHA-256",
        en:"A purpose-built function such as Argon2 or bcrypt rather than SHA-256"},c:1}],
 e:{sv:"Snabbhet är en dygd för en checksumma och ett fel för en lösenordshash. SHA-256 är snabb — precis därför är den fel verktyg här.",
    en:"Speed is a virtue for a checksum and a defect for a password hash. SHA-256 is fast, which is exactly why it is the wrong tool here."}}]},

{tier:{sv:"Nycklar och certifikat", en:"Keys and certificates"}, items:[

{q:{sv:"Vad intygar egentligen en certifikatutfärdare?",
    en:"What does a certificate authority actually assert?"},
 o:[{t:{sv:"Att den här publika nyckeln hör till det här namngivna subjektet",
        en:"That this public key belongs to this named subject"},c:1},
    {t:{sv:"Att subjektet är pålitligt", en:"That the subject is trustworthy"}},
    {t:{sv:"Att den privata nyckeln aldrig läckt", en:"That the private key has never leaked"}},
    {t:{sv:"En signatur ditt system litar på för att det litar på utfärdaren",
        en:"A signature your system trusts because it trusts the CA"},c:1}],
 e:{sv:"Ett certifikat binder en identitet till en nyckel. Det är ingen karaktärsreferens, och det kan inte veta om den privata nyckeln fortfarande är hemlig.",
    en:"A certificate binds an identity to a key. It is not a character reference, and it cannot know whether the private key is still secret."}},

{q:{sv:"Varför har certifikat ett utgångsdatum?", en:"Why does a certificate have an expiry date?"},
 o:[{t:{sv:"Det begränsar skadan om en privat nyckel läckt utan att någon märkt det",
        en:"It bounds the damage if the private key leaks without anyone noticing"},c:1},
    {t:{sv:"Det tvingar fram återkommande omprövning av bindningen",
        en:"It forces periodic re-verification of the binding"},c:1},
    {t:{sv:"För att matematiken slutar fungera efter ett tag",
        en:"Because the maths stops working after a while"}},
    {t:{sv:"Det gör att algoritmer kan fasas ut över tid",
        en:"It allows algorithms to be retired over time"},c:1}],
 e:{sv:"Utgångsdatum är ett trubbigt men pålitligt skyddsnät för spärrlistor, som fungerar dåligt i praktiken.",
    en:"Expiry is a blunt but reliable backstop for revocation, which is notoriously unreliable in practice."}},

{q:{sv:"Data «i vila» kontra «i transit» — vad är skillnaden i praktiken?",
    en:"Data at rest versus in transit — what is the practical difference?"},
 o:[{t:{sv:"I vila är lagrad data; i transit är data på väg över ett nät",
        en:"At rest is stored data; in transit is data moving over a network"},c:1},
    {t:{sv:"Diskkryptering skyddar i vila, och bara medan maskinen är avstängd",
        en:"Full-disk encryption protects at rest, and only while the machine is off"},c:1},
    {t:{sv:"TLS skyddar i transit men inte när datan väl landat",
        en:"TLS protects in transit but not once the data has landed"},c:1},
    {t:{sv:"Kryptering i vila skyddar även i transit",
        en:"Encrypting at rest also protects in transit"}}],
 e:{sv:"Vanligaste misstaget är att tro att det ena täcker det andra. En igångvarande server med krypterad disk ger en angripare med skal exakt samma åtkomst som en okrypterad.",
    en:"The common mistake is thinking one covers the other. A running server with an encrypted disk gives an attacker with a shell exactly the same access as an unencrypted one."}},

{q:{sv:"Vad bör ske när en privat nyckel misstänks ha läckt?",
    en:"What should happen when a private key is suspected to have leaked?"},
 o:[{t:{sv:"Spärra certifikatet och skapa ett nytt nyckelpar",
        en:"Revoke the certificate and issue a new key pair"},c:1},
    {t:{sv:"Utred vad nyckeln kan ha använts till under tiden",
        en:"Investigate what the key could have been used for while exposed"},c:1},
    {t:{sv:"Byt lösenfras på nyckeln och fortsätt använda den",
        en:"Change the password on the key and keep using it"}},
    {t:{sv:"Behandla allt som signerats efter exponeringen som opålitligt",
        en:"Treat everything signed with it after the exposure as untrustworthy"},c:1}],
 e:{sv:"En läckt nyckel går inte att laga. Lösenfrasen skyddar bara filen — när nyckelmaterialet är ute är byte enda boten.",
    en:"A leaked key is not repairable. The passphrase only protects the file — once the key material is out, the only cure is replacement."}}]}],

hotanalys: [
{tier:{sv:"Hotbilden", en:"The threat picture"}, items:[

{q:{sv:"Vad står CIA-triaden för?", en:"What does the CIA triad name?"},
 o:[{t:{sv:"Sekretess — bara behöriga kan läsa",
        en:"Confidentiality — only those entitled can read it"},c:1},
    {t:{sv:"Riktighet — det har inte ändrats oupptäckt",
        en:"Integrity — it has not been altered undetectably"},c:1},
    {t:{sv:"Tillgänglighet — det finns där när det behövs",
        en:"Availability — it is there when needed"},c:1},
    {t:{sv:"Autentisering, identifiering och auktorisation",
        en:"Authentication, identification and authorisation"}}],
 e:{sv:"Nästan varje skyddsåtgärd tjänar en av de tre, och de drar åt olika håll — det mest sekretessbevarande systemet är ett som ingen kommer åt.",
    en:"Nearly every control serves one of these three, and they pull against each other — the most confidential system is one nobody can reach."}},

{q:{sv:"Hur skiljer sig hot, sårbarhet och risk?",
    en:"How do threat, vulnerability and risk differ?"},
 o:[{t:{sv:"Ett hot är något som skulle kunna orsaka skada",
        en:"A threat is something that could cause harm"},c:1},
    {t:{sv:"En sårbarhet är en svaghet ett hot kan utnyttja",
        en:"A vulnerability is a weakness that a threat could use"},c:1},
    {t:{sv:"Risk kombinerar sannolikhet med konsekvens",
        en:"Risk combines how likely it is with how much it would hurt"},c:1},
    {t:{sv:"Orden betyder samma sak", en:"They are interchangeable words"}}],
 e:{sv:"En sårbarhet utan troligt hot är låg risk. Att rapportera en skannerlista som «risker» hoppar över hela det här steget.",
    en:"A vulnerability with no plausible threat is low risk. Reporting a scanner's raw findings as 'risks' skips this step entirely."}},

{q:{sv:"Varför är social manipulation så effektiv?",
    en:"Why is social engineering so effective?"},
 o:[{t:{sv:"Den riktar sig mot människor, som inte går att patcha",
        en:"It targets people, who are not patchable"},c:1},
    {t:{sv:"Den utnyttjar hjälpsamhet, auktoritet och tidspress",
        en:"It exploits helpfulness, authority and time pressure"},c:1},
    {t:{sv:"Den kräver ingen teknisk sårbarhet alls",
        en:"It requires no technical vulnerability at all"},c:1},
    {t:{sv:"Den fungerar bara på outbildad personal",
        en:"It only works on untrained staff"}}],
 e:{sv:"Utbildade går också på det, särskilt under press. Därför är svaret rutiner — verifiera i en annan kanal — snarare än att förvänta sig ständig vaksamhet.",
    en:"Trained people fall for it too, especially under pressure. Which is why the answer is process — verify out of band — rather than expecting constant alertness."}},

{q:{sv:"Vad används MITRE ATT&CK till?", en:"What is MITRE ATT&CK used for?"},
 o:[{t:{sv:"En katalog över de tekniker angripare faktiskt använder, ordnad efter taktik",
        en:"A catalogue of the techniques attackers actually use, organised by tactic"},c:1},
    {t:{sv:"Att beskriva vad en angripare gjort med gemensamt språk",
        en:"Describing what an attacker did in shared vocabulary"},c:1},
    {t:{sv:"Att pröva vilka tekniker ni faktiskt kan upptäcka",
        en:"Checking which techniques you can currently detect"},c:1},
    {t:{sv:"Att poängsätta hur allvarlig en sårbarhet är",
        en:"Scoring how severe a vulnerability is"}}],
 e:{sv:"Allvarlighetsgrad är CVSS. ATT&CK handlar om beteende: det låter dig fråga «skulle vi se det här?» i stället för «är vi patchade?».",
    en:"Severity scoring is CVSS. ATT&CK is about behaviour: it lets you ask 'could we see this?' rather than 'are we patched?'"}}]},

{tier:{sv:"Riskarbete", en:"Working with risk"}, items:[

{q:{sv:"Risk uttrycks ofta som sannolikhet gånger konsekvens. Vad missar det?",
    en:"Risk is often expressed as likelihood times impact. What does that miss?"},
 o:[{t:{sv:"Sällsynta händelser med katastrofal konsekvens medelvärdesbildas bort",
        en:"Rare events with catastrophic impact get averaged into insignificance"},c:1},
    {t:{sv:"Båda faktorerna är uppskattningar, inte mätvärden",
        en:"Both factors are estimates, not measurements"},c:1},
    {t:{sv:"Det är ett sätt att rangordna, inte en fysisk storhet",
        en:"It is a way to rank, not a physical quantity"},c:1},
    {t:{sv:"Ingenting — det är exakt", en:"Nothing — it is exact"}}],
 e:{sv:"Det är ett verktyg för att jämföra och prioritera, inte för att förutsäga. Att behandla utfallet som ett tal snarare än en ordning är där riskregister spårar ur.",
    en:"It is a tool for comparing and prioritising, not for predicting. Treating the output as a number rather than an ordering is where risk registers go wrong."}},

{q:{sv:"Vilka sätt finns att hantera en risk?",
    en:"What are the recognised ways to treat a risk?"},
 o:[{t:{sv:"Minska den med skyddsåtgärder", en:"Reduce it with controls"},c:1},
    {t:{sv:"Överföra den, till exempel genom försäkring eller outsourcing",
        en:"Transfer it, for example by insuring or outsourcing"},c:1},
    {t:{sv:"Undvika den genom att låta bli det riskabla",
        en:"Avoid it by not doing the risky thing"},c:1},
    {t:{sv:"Acceptera den, medvetet och dokumenterat",
        en:"Accept it, deliberately and on the record"},c:1},
    {t:{sv:"Eskalera den uppåt så att den blir någon annans problem",
        en:"Escalate it upwards so it becomes someone else's problem"}}],
 e:{sv:"Alla fyra är legitima. Acceptans är ett beslut som någon med mandat fattar och skriver under — inte samma sak som att strunta i den.",
    en:"All four are legitimate. Acceptance is a decision someone with authority makes and signs — not the same as ignoring it."}},

{q:{sv:"Vad hjälper STRIDE dig med?", en:"What does STRIDE help you do?"},
 o:[{t:{sv:"Att gå igenom kategorier av hot mot en konstruktion",
        en:"Work through categories of threat against a design"},c:1},
    {t:{sv:"Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege",
        en:"Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege"},c:1},
    {t:{sv:"Att poängsätta sårbarheter", en:"Score vulnerabilities for severity"}},
    {t:{sv:"Att ställa systematiska frågor tidigt, när en design är billig att ändra",
        en:"Ask systematic questions early, when a design is still cheap to change"},c:1}],
 e:{sv:"Hotmodellering lönar sig bäst innan något byggts. Ett designfel som hittas i produktion kostar enormt mycket mer än ett som hittas på en whiteboard.",
    en:"Threat modelling pays best before anything is built. A design flaw found in production costs enormously more than one found on a whiteboard."}},

{q:{sv:"Vad innebär djupförsvar?", en:"What does defence in depth mean?"},
 o:[{t:{sv:"Flera oberoende skyddsåtgärder, så att ett fel inte blir totalt",
        en:"Several independent controls, so one failure is not total failure"},c:1},
    {t:{sv:"Att anta att varje enskild åtgärd förr eller senare kringgås",
        en:"Assuming any single control will eventually be bypassed"},c:1},
    {t:{sv:"Att köpa fler produkter", en:"Buying more products"}},
    {t:{sv:"Lager som fallerar på olika sätt snarare än på samma",
        en:"Layers that fail in different ways rather than the same way"},c:1}],
 e:{sv:"Lager hjälper bara om de är verkligt oberoende. Tre produkter från samma leverantör med samma brist är ett lager med tre etiketter.",
    en:"Layers only help if they are genuinely independent. Three products from the same vendor sharing one flawed engine is one layer wearing three badges."}}]}]
,
pentest: [
{tier:{sv:"Metod och mandat", en:"Method and mandate"}, items:[

{q:{sv:"Vad måste finnas på plats innan testning påbörjas?",
    en:"What must exist before any testing starts?"},
 o:[{t:{sv:"Skriftligt tillstånd från någon som har rätt att ge det",
        en:"Written authorisation from someone entitled to give it"},c:1},
    {t:{sv:"En överenskommen omfattning som anger vad som ingår och inte",
        en:"An agreed scope naming what is in and out"},c:1},
    {t:{sv:"En kontaktväg för när något går sönder",
        en:"A contact for when something breaks"},c:1},
    {t:{sv:"Inget, om avsikten är god", en:"Nothing, if you intend no harm"}}],
 e:{sv:"Utan skriftligt tillstånd är samma handlingar brottsliga. Avsikt är ingen ursäkt, och «jag ville hjälpa till» är ingen omfattningsöverenskommelse.",
    en:"Without written authorisation, the same actions are a crime. Intent is not a defence, and 'I was helping' is not a scope agreement."}},

{q:{sv:"Vad skiljer en sårbarhetsskanning från ett penetrationstest?",
    en:"What separates a vulnerability scan from a penetration test?"},
 o:[{t:{sv:"Skanningen listar möjliga svagheter; testet försöker använda dem",
        en:"A scan lists possible weaknesses; a test tries to use them"},c:1},
    {t:{sv:"Skanning är i hög grad automatisk, test bygger på mänskligt omdöme",
        en:"A scan is largely automated, a test relies on human judgement"},c:1},
    {t:{sv:"Skanningen bevisar utnyttjbarhet", en:"A scan proves exploitability"}},
    {t:{sv:"Ett test kan kedja ihop små fynd till ett allvarligt",
        en:"A test can chain small findings into a serious one"},c:1}],
 e:{sv:"Kedjandet är testarens verkliga värde. Tre fynd som en skanner kallar «låg» kan tillsammans ge full kompromettering, vilket ingen skanner berättar.",
    en:"Chaining is the real value of a human tester. Three findings a scanner rates 'low' can combine into full compromise, which no scanner will tell you."}},

{q:{sv:"Black box, grey box, white box — vad betyder de?",
    en:"Black box, grey box, white box — what do they mean?"},
 o:[{t:{sv:"Black box: ingen förhandsinformation, närmast en utomstående angripare",
        en:"Black box: no prior information, closest to an outside attacker"},c:1},
    {t:{sv:"White box: full information, källkod och arkitektur inkluderad",
        en:"White box: full information, source and architecture included"},c:1},
    {t:{sv:"Grey box: delvis kunskap, till exempel ett vanligt användarkonto",
        en:"Grey box: partial knowledge, such as a normal user account"},c:1},
    {t:{sv:"Black box hittar alltid mest", en:"Black box always finds more"}}],
 e:{sv:"Black box lägger stor del av budgeten på att upptäcka det white box får veta dag ett. Mer realism är inte samma sak som fler fynd per krona.",
    en:"Black box spends much of the budget discovering what white box is told on day one. More realism is not the same as more findings per krona."}},

{q:{sv:"Ett test hittar ingenting. Vad betyder det?",
    en:"A test finds nothing. What does that mean?"},
 o:[{t:{sv:"Att den här testaren, på den här tiden, inom den här omfattningen, inte fann något",
        en:"That this tester, in this time, within this scope, found nothing"},c:1},
    {t:{sv:"Att systemet är säkert", en:"That the system is secure"}},
    {t:{sv:"Det säger lika mycket om testet som om målet",
        en:"It is a statement about the test as much as the target"},c:1},
    {t:{sv:"Det kan säga mer om omfattning och tid än om försvaret",
        en:"It may say more about scope or time than about defences"},c:1}],
 e:{sv:"Frånvaro av bevis är inte bevis på frånvaro. En ren rapport är en ögonblicksbild som slutar gälla så snart något ändras.",
    en:"Absence of evidence is not evidence of absence. A clean report is a snapshot, and it expires the moment anything changes."}}]},

{tier:{sv:"Arbetsgången", en:"How the work runs"}, items:[

{q:{sv:"Vad är rekognosering, och varför kommer den först?",
    en:"What is reconnaissance, and why does it come first?"},
 o:[{t:{sv:"Att samla information om målet innan man rör det",
        en:"Gathering information about the target before touching it"},c:1},
    {t:{sv:"Passiv rekognosering använder öppna källor och syns inte hos målet",
        en:"Passive recon uses public sources and leaves no trace on the target"},c:1},
    {t:{sv:"Den formar allt därefter — du kan inte testa det du inte hittat",
        en:"It shapes everything after — you cannot test what you have not found"},c:1},
    {t:{sv:"Den är valfri om man har en mållista",
        en:"It is optional if you have a target list"}}],
 e:{sv:"Den bortglömda underdomänen som ingen inventerat är en återkommande väg in. Rekognosering är hur testaren hittar den före någon annan.",
    en:"The forgotten subdomain nobody inventoried is a recurring way in. Recon is how the tester finds it before someone else does."}},

{q:{sv:"Vad ger CVSS dig, och vad ger det inte?",
    en:"What does CVSS give you, and what does it not?"},
 o:[{t:{sv:"En standardiserad allvarlighetspoäng för en sårbarhet",
        en:"A standard severity score for a vulnerability"},c:1},
    {t:{sv:"En grundpoäng som bortser från just din miljö",
        en:"A base score that ignores your specific environment"},c:1},
    {t:{sv:"Din faktiska risk", en:"Your actual risk"}},
    {t:{sv:"Ett gemensamt språk för att jämföra fynd",
        en:"A common language for comparing findings"},c:1}],
 e:{sv:"En 9.8:a på en labbmaskin utan data kan betyda mindre än en 5.3:a på systemet med kunduppgifterna. Poängen är indata till risk, inte risken själv.",
    en:"A 9.8 on a lab machine with no data may matter less than a 5.3 on the system holding customer records. The score is an input to risk, not risk itself."}},

{q:{sv:"Vad är privilegieeskalering?", en:"What is privilege escalation?"},
 o:[{t:{sv:"Att förvandla begränsad åtkomst till större",
        en:"Turning limited access into greater access"},c:1},
    {t:{sv:"Vertikal: från användare till administratör eller root",
        en:"Vertical: from user to administrator or root"},c:1},
    {t:{sv:"Horisontell: att nå en annan användares data på samma nivå",
        en:"Horizontal: reaching another user's data at the same level"},c:1},
    {t:{sv:"Bara relevant på Linux", en:"Only relevant on Linux"}}],
 e:{sv:"Första åtkomsten är sällan det intressanta. Det som betyder något är vad ett vanligt fotfäste kan förvandlas till — därför får SUID-binärer och svaga tjänsterättigheter så mycket uppmärksamhet.",
    en:"Initial access is rarely the interesting part. What matters is what an ordinary foothold can be turned into — which is why SUID binaries and weak service permissions get so much attention."}},

{q:{sv:"Vad hör hemma i en penetrationstestrapport?",
    en:"What belongs in a penetration test report?"},
 o:[{t:{sv:"Vad som hittades, med detaljer nog att återskapa det",
        en:"What was found, with enough detail to reproduce it"},c:1},
    {t:{sv:"Vad det betyder i verksamhetstermer, inte bara tekniskt",
        en:"What it means in business terms, not only technical severity"},c:1},
    {t:{sv:"Tydliga åtgärdsförslag", en:"Clear remediation advice"},c:1},
    {t:{sv:"All rå verktygsutdata, ofiltrerad", en:"Every raw tool output, unfiltered"}}],
 e:{sv:"Rapporten är leveransen — testandet är bara hur den tas fram. Ett fynd ingen kan återskapa eller åtgärda har inget värde.",
    en:"The report is the deliverable — the testing is just how you produce it. A finding nobody can reproduce or act on has no value."}}]}],

incident: [
{tier:{sv:"Incidenthantering", en:"Handling the incident"}, items:[

{q:{sv:"Vilka faser har incidenthantering?", en:"What are the phases of incident response?"},
 o:[{t:{sv:"Förberedelse, innan något hänt", en:"Preparation, before anything happens"},c:1},
    {t:{sv:"Upptäckt och analys", en:"Detection and analysis"},c:1},
    {t:{sv:"Begränsning, utrensning och återställning",
        en:"Containment, eradication and recovery"},c:1},
    {t:{sv:"Erfarenhetsåterföring efteråt", en:"Lessons learned afterwards"},c:1},
    {t:{sv:"Attribution — att fastställa vilken grupp som låg bakom",
        en:"Attribution — establishing which group was behind it"}}],
 e:{sv:"Förberedelsen är den fas som avgör hur de andra går. En organisation som tänker på detta först under en incident har redan hamnat på efterkälken.",
    en:"Preparation is the phase that decides how the others go. An organisation that first thinks about this during an incident is already losing."}},

{q:{sv:"Varför är begränsning oftast det första man gör?",
    en:"Why is containment usually the immediate priority?"},
 o:[{t:{sv:"Det stoppar spridningen medan man reder ut vad som hänt",
        en:"It stops the damage spreading while you work out what happened"},c:1},
    {t:{sv:"Att förstå hela incidenten tar mycket längre tid än att stoppa den",
        en:"Understanding the whole incident takes far longer than stopping it"},c:1},
    {t:{sv:"För att man alltid ska stänga av strömmen direkt",
        en:"Because you must always power off immediately"}},
    {t:{sv:"Det köper tid utan att förstöra det du behöver för utredningen",
        en:"It buys time without destroying what you need to investigate"},c:1}],
 e:{sv:"Att dra ur strömmen är begränsning och bevisförstöring på en gång — flyktigt minne är borta. Att isolera från nätet ger oftast mer och kostar mindre.",
    en:"Pulling the power is containment and evidence destruction at once — volatile memory is gone. Isolating from the network usually achieves more, and costs less."}},

{q:{sv:"Varför är bevishantering viktig under en incident?",
    en:"What makes evidence handling important during an incident?"},
 o:[{t:{sv:"Fynden kan hamna i en rättslig process",
        en:"Findings may end up in a legal process"},c:1},
    {t:{sv:"Spårbarhetskedjan visar vem som haft vad, och när",
        en:"Chain of custody records who had what, when"},c:1},
    {t:{sv:"Att arbeta på kopior bevarar originalets tillstånd",
        en:"Working on copies preserves the original state"},c:1},
    {t:{sv:"Det spelar bara roll om man tänker åtala",
        en:"It only matters if you intend to prosecute"}}],
 e:{sv:"Man vet sällan i början om det slutar i domstol, ett försäkringsärende eller hos en tillsynsmyndighet. När man vet är det för sent att börja vara noggrann.",
    en:"You rarely know at the start whether it ends in court, an insurance claim or a regulator's questions. By the time you know, it is too late to start being careful."}},

{q:{sv:"Vad är syftet med en genomgång efter incidenten?",
    en:"What is the point of a post-incident review?"},
 o:[{t:{sv:"Att hitta vad som bör ändras så samma sak blir svårare nästa gång",
        en:"Finding what to change so the same thing is harder next time"},c:1},
    {t:{sv:"Att förbättra själva hanteringen, inte bara försvaret",
        en:"Improving the response itself, not only the defences"},c:1},
    {t:{sv:"Att peka ut vem som klickade", en:"Assigning blame to whoever clicked"}},
    {t:{sv:"Att dokumentera tidslinjen medan den är färsk",
        en:"Recording the timeline while it is still fresh"},c:1}],
 e:{sv:"Skuldinriktade genomgångar lär folk att dölja incidenter, vilket är raka motsatsen till vad man behöver. Den som snabbt rapporterar sitt eget misstag gör precis rätt.",
    en:"Blame-focused reviews teach people to hide incidents, which is the opposite of what you need. The person who reports their own mistake quickly is doing exactly the right thing."}}]},

{tier:{sv:"Kontinuitet och återställning", en:"Continuity and recovery"}, items:[

{q:{sv:"Vad mäter RTO och RPO?", en:"What do RTO and RPO measure?"},
 o:[{t:{sv:"RTO: hur lång tid ni får ta på er att återställa tjänsten",
        en:"RTO: how long you may take to restore service"},c:1},
    {t:{sv:"RPO: hur mycket data ni får förlora, mätt i tid",
        en:"RPO: how much data you may lose, measured in time"},c:1},
    {t:{sv:"RPO är i praktiken ett uttalande om hur ofta ni säkerhetskopierar",
        en:"RPO is really a statement about backup frequency"},c:1},
    {t:{sv:"De betyder samma sak", en:"They are the same thing"}}],
 e:{sv:"Ett RPO på en timme och en nattlig säkerhetskopiering går inte ihop. Att upptäcka det i planen är mycket billigare än att upptäcka det under återställningen.",
    en:"An RPO of one hour and a nightly backup are incompatible, and noticing that in the plan is much cheaper than noticing it during recovery."}},

{q:{sv:"Vad innebär 3-2-1-regeln för säkerhetskopior?",
    en:"What is the 3-2-1 backup rule?"},
 o:[{t:{sv:"Tre kopior av datan", en:"Three copies of the data"},c:1},
    {t:{sv:"På två olika sorters media", en:"On two different kinds of media"},c:1},
    {t:{sv:"Med en kopia på annan plats", en:"With one copy off site"},c:1},
    {t:{sv:"Sparade i tre år", en:"Kept for three years"}}],
 e:{sv:"Utpressningsprogram lade till en följdsats: en kopia bör vara frånkopplad eller oföränderlig, eftersom allt som nås från det komprometterade nätet också kan krypteras.",
    en:"Ransomware added a corollary: one copy should be offline or immutable, since anything reachable from the compromised network can be encrypted too."}},

{q:{sv:"Varför måste en säkerhetskopia återläsas innan den räknas?",
    en:"Why must a backup be restored before it counts as a backup?"},
 o:[{t:{sv:"Kopieringsjobb rapporterar framgång och producerar ändå oanvändbart resultat",
        en:"Backup jobs report success while producing unusable output"},c:1},
    {t:{sv:"Återläsningen är den del som har en deadline, så den måste övas",
        en:"Restoring is the part with a deadline, so it must be rehearsed"},c:1},
    {t:{sv:"Man upptäcker saknade delar först genom att pröva",
        en:"You discover missing pieces only by trying"},c:1},
    {t:{sv:"En lyckad jobblogg är tillräckligt bevis",
        en:"A successful job log is sufficient proof"}}],
 e:{sv:"Felet är sällan «ingen backup» — det är «en backup som ingen någonsin återläst». Rutinen är leveransen, inte arkivet.",
    en:"The failure mode is rarely 'no backup' — it is 'a backup nobody had ever restored'. The procedure is the deliverable, not the archive."}},

{q:{sv:"Vad är en konsekvensanalys för verksamheten till för?",
    en:"What is a business impact analysis for?"},
 o:[{t:{sv:"Att reda ut vilka processer som betyder mest och hur snabbt de måste tillbaka",
        en:"Working out which processes matter most and how quickly they must return"},c:1},
    {t:{sv:"Att grunda återställningsordningen i verksamheten i stället för i IT-preferenser",
        en:"Basing recovery priorities on the business rather than on IT preference"},c:1},
    {t:{sv:"Att lista varje server ni äger", en:"Listing every server you own"}},
    {t:{sv:"Att hitta beroenden man inte visste att en process hade",
        en:"Finding dependencies you did not know a process had"},c:1}],
 e:{sv:"Återställningsordningen bör följa verksamhetens behov. Utan analys följer den i stället vems system som ägs av den som låter mest.",
    en:"Recovery order should follow business impact. Without a BIA it tends to follow whichever system the loudest person owns."}}]}],

ledningssystem: [
{tier:{sv:"Ledningssystemet", en:"The management system"}, items:[

{q:{sv:"Vad är skillnaden mellan ISO 27001 och ISO 27002?",
    en:"What is the difference between ISO 27001 and ISO 27002?"},
 o:[{t:{sv:"27001 anger krav på ledningssystemet och går att certifiera mot",
        en:"27001 sets requirements for the management system and can be certified against"},c:1},
    {t:{sv:"27002 är vägledning om själva skyddsåtgärderna",
        en:"27002 is guidance on the controls themselves"},c:1},
    {t:{sv:"De är samma standard i två upplagor",
        en:"They are the same standard in two editions"}},
    {t:{sv:"Man certifierar sig mot 27002", en:"You certify against 27002"}}],
 e:{sv:"27001 säger vad som måste finnas på plats; 27002 föreslår hur. Certifiering avser alltid 27001.",
    en:"27001 says what must be in place; 27002 suggests how. Certification is always against 27001."}},

{q:{sv:"Vad innebär PDCA i ett ledningssystem?",
    en:"What does PDCA mean in a management system?"},
 o:[{t:{sv:"Planera, Genomför, Följ upp, Förbättra — i en återkommande cykel",
        en:"Plan, Do, Check, Act — as a repeating cycle"},c:1},
    {t:{sv:"Att säkerhetsarbetet är ett tillstånd som underhålls, inte ett projekt som avslutas",
        en:"That security is a state you maintain, not a project you finish"},c:1},
    {t:{sv:"En engångsgenomgång inför certifiering",
        en:"A one-off review before certification"}},
    {t:{sv:"Att uppföljning ska leda till konkreta ändringar",
        en:"That checking should lead to actual change"},c:1}],
 e:{sv:"Den vanligaste bristen är att stanna vid Check: avvikelser noteras men inget ändras, och nästa revision hittar samma sak.",
    en:"The common failure is stopping at Check: findings are noted but nothing changes, and the next audit finds the same things."}},

{q:{sv:"Vad är ett uttalande om tillämplighet (SoA)?",
    en:"What is a Statement of Applicability?"},
 o:[{t:{sv:"En förteckning över vilka skyddsåtgärder som gäller er, och varför",
        en:"A record of which controls apply to you, and why"},c:1},
    {t:{sv:"Det ska motivera även de åtgärder ni valt bort",
        en:"It must justify the controls you excluded too"},c:1},
    {t:{sv:"En lista över era servrar", en:"A list of your servers"}},
    {t:{sv:"Kopplingen mellan riskbedömningen och valda åtgärder",
        en:"The link between the risk assessment and the chosen controls"},c:1}],
 e:{sv:"SoA är där riskarbetet möter åtgärderna. Ett bortval utan motivering är den enklaste avvikelsen en revisor kan hitta.",
    en:"The SoA is where risk work meets controls. An exclusion without a justification is the easiest finding an auditor can write."}},

{q:{sv:"Varför betonar standarderna ledningens engagemang?",
    en:"Why do the standards emphasise management commitment?"},
 o:[{t:{sv:"Säkerhetsarbete kostar pengar och tid som någon måste besluta om",
        en:"Security work costs money and time that someone must authorise"},c:1},
    {t:{sv:"Utan mandat blir det rekommendationer som ingen följer",
        en:"Without a mandate it becomes recommendations nobody follows"},c:1},
    {t:{sv:"För att ledningen ska utföra det tekniska arbetet",
        en:"So that management does the technical work"}},
    {t:{sv:"Riskacceptans måste beslutas av någon med befogenhet",
        en:"Risk acceptance must be decided by someone with authority"},c:1}],
 e:{sv:"En säkerhetsfunktion utan mandat kan beskriva problemen men inte lösa dem. Därför är ledningens ansvar ett krav och inte en artighetsfras.",
    en:"A security function without a mandate can describe problems but not fix them. That is why management responsibility is a requirement, not a courtesy."}}]},

{tier:{sv:"Systematiskt arbetssätt", en:"Working systematically"}, items:[

{q:{sv:"Vad skiljer en policy från en rutin?",
    en:"What separates a policy from a procedure?"},
 o:[{t:{sv:"Policyn anger vad som gäller och varför",
        en:"A policy states what applies, and why"},c:1},
    {t:{sv:"Rutinen beskriver hur det görs, steg för steg",
        en:"A procedure describes how it is done, step by step"},c:1},
    {t:{sv:"De är utbytbara ord", en:"They are interchangeable words"}},
    {t:{sv:"Policyer ändras sällan, rutiner ofta",
        en:"Policies change rarely, procedures often"},c:1}],
 e:{sv:"En policy utan rutiner blir en avsiktsförklaring. Rutiner utan policy blir vanor som ingen kan motivera.",
    en:"A policy without procedures is a statement of intent. Procedures without a policy are habits nobody can justify."}},

{q:{sv:"Varför är en tillgångsförteckning grundläggande?",
    en:"Why is an asset register foundational?"},
 o:[{t:{sv:"Man kan inte skydda det man inte vet att man har",
        en:"You cannot protect what you do not know you have"},c:1},
    {t:{sv:"Den kopplar system till ägare och till verksamhetsvärde",
        en:"It ties systems to owners and to business value"},c:1},
    {t:{sv:"Den behöver bara innehålla hårdvara",
        en:"It only needs to contain hardware"}},
    {t:{sv:"Okända system är där incidenter oproportionerligt ofta börjar",
        en:"Unknown systems are where incidents disproportionately start"},c:1}],
 e:{sv:"Information, tjänster och leverantörsberoenden är också tillgångar. Den bortglömda servern utan ägare är ett återkommande tema i incidentrapporter.",
    en:"Information, services and supplier dependencies are assets too. The forgotten server with no owner is a recurring theme in incident reports."}},

{q:{sv:"Vad är intern revision till för?", en:"What is internal audit for?"},
 o:[{t:{sv:"Att pröva om det som står i systemet också sker i praktiken",
        en:"Testing whether what the system says also happens in practice"},c:1},
    {t:{sv:"Att hitta avvikelser innan en extern revisor gör det",
        en:"Finding nonconformities before an external auditor does"},c:1},
    {t:{sv:"Att bevisa att allt är perfekt", en:"To prove everything is perfect"}},
    {t:{sv:"Den bör utföras av någon som inte granskar sitt eget arbete",
        en:"It should be done by someone not reviewing their own work"},c:1}],
 e:{sv:"En revision som aldrig hittar något är oftast ett tecken på svag revision, inte på ett felfritt system.",
    en:"An audit that never finds anything is usually a sign of a weak audit, not a flawless system."}},

{q:{sv:"Vad kännetecknar ett moget säkerhetsarbete?",
    en:"What characterises mature security work?"},
 o:[{t:{sv:"Beslut fattas utifrån risk snarare än utifrån senaste larmet",
        en:"Decisions follow risk rather than the latest scare"},c:1},
    {t:{sv:"Det finns spårbarhet: varför en åtgärd finns går att förklara",
        en:"There is traceability: why a control exists can be explained"},c:1},
    {t:{sv:"Att äga flest säkerhetsprodukter", en:"Owning the most security products"}},
    {t:{sv:"Arbetet fortsätter fungera när nyckelpersonen är sjuk",
        en:"The work keeps functioning when the key person is away"},c:1}],
 e:{sv:"Beroendet av en enskild eldsjäl är en risk i sig. Dokumenterade rutiner är vad som skiljer en funktion från en person.",
    en:"Dependence on a single enthusiast is itself a risk. Documented procedure is what separates a function from a person."}}]}]
,
kravstallning: [
{tier:{sv:"Att ställa krav", en:"Writing requirements"}, items:[

{q:{sv:"Vad skiljer funktionella från icke-funktionella krav?",
    en:"What separates functional from non-functional requirements?"},
 o:[{t:{sv:"Funktionella beskriver vad systemet ska göra",
        en:"Functional requirements describe what the system must do"},c:1},
    {t:{sv:"Icke-funktionella beskriver hur väl det ska göras",
        en:"Non-functional requirements describe how well it must do it"},c:1},
    {t:{sv:"Säkerhet, prestanda och tillgänglighet hör oftast till de icke-funktionella",
        en:"Security, performance and availability are usually non-functional"},c:1},
    {t:{sv:"Icke-funktionella krav är mindre viktiga",
        en:"Non-functional requirements matter less"}}],
 e:{sv:"Det är oftast de icke-funktionella kraven som avgör om ett system går att driva. De glöms bort just för att de inte syns i en demo.",
    en:"It is usually the non-functional requirements that decide whether a system can be operated. They get forgotten precisely because they do not show in a demo."}},

{q:{sv:"Vad kännetecknar ett bra säkerhetskrav?",
    en:"What makes a good security requirement?"},
 o:[{t:{sv:"Det går att verifiera — man kan avgöra om det är uppfyllt",
        en:"It is verifiable — you can tell whether it is met"},c:1},
    {t:{sv:"Det är entydigt formulerat", en:"It is unambiguous"},c:1},
    {t:{sv:"Det anger «systemet ska vara säkert»",
        en:"It states that 'the system shall be secure'"}},
    {t:{sv:"Det knyter an till ett identifierat behov eller en risk",
        en:"It ties back to an identified need or risk"},c:1}],
 e:{sv:"«Ska vara säkert» går inte att pröva och betyder därför ingenting i en upphandling. «Ska stödja federerad inloggning via SAML 2.0» går att pröva.",
    en:"'Shall be secure' cannot be tested and therefore means nothing in a procurement. 'Shall support federated login via SAML 2.0' can be tested."}},

{q:{sv:"Vad bör ett servicenivåavtal (SLA) faktiskt reglera?",
    en:"What should a service level agreement actually cover?"},
 o:[{t:{sv:"Vad som utlovas, mätt på ett sätt båda parter kan följa upp",
        en:"What is promised, measured in a way both parties can follow up"},c:1},
    {t:{sv:"Vad som händer när nivån inte hålls",
        en:"What happens when the level is not met"},c:1},
    {t:{sv:"Endast leverantörens ambition", en:"Only the supplier's ambition"}},
    {t:{sv:"Svarstider för incidenter, inte bara drifttid",
        en:"Response times for incidents, not only uptime"},c:1}],
 e:{sv:"99,9 procents drifttid utan definition av vad «uppe» betyder, eller vad som händer vid brott, är en siffra utan innehåll.",
    en:"99.9 percent uptime, with no definition of what 'up' means or what happens when it is breached, is a number without content."}},

{q:{sv:"Vad är viktigt vid bedömning av en leverantörs säkerhet?",
    en:"What matters when assessing a supplier's security?"},
 o:[{t:{sv:"Att deras brister blir era brister",
        en:"That their weaknesses become your weaknesses"},c:1},
    {t:{sv:"Vad som gäller när avtalet upphör — datauttag och radering",
        en:"What happens when the contract ends — data export and deletion"},c:1},
    {t:{sv:"Ett certifikat räcker som bevis", en:"A certificate is proof enough"}},
    {t:{sv:"Om de i sin tur är beroende av underleverantörer",
        en:"Whether they in turn depend on subcontractors"},c:1}],
 e:{sv:"Ett certifikat säger att ett ledningssystem finns inom en viss omfattning — inte att just er tjänst omfattas. Fråga alltid vad omfattningen är.",
    en:"A certificate says a management system exists within some scope — not that your particular service is inside it. Always ask what the scope is."}}]},

{tier:{sv:"Upphandling och kalkyl", en:"Procurement and costing"}, items:[

{q:{sv:"Vad ingår i total ägandekostnad (TCO)?",
    en:"What goes into total cost of ownership?"},
 o:[{t:{sv:"Inköp eller licens", en:"Purchase or licence"},c:1},
    {t:{sv:"Drift, underhåll och support över hela livslängden",
        en:"Operation, maintenance and support across the lifetime"},c:1},
    {t:{sv:"Utbildning och den tid personalen lägger",
        en:"Training and the time staff spend"},c:1},
    {t:{sv:"Avveckling och migrering vid byte",
        en:"Decommissioning and migration when you move on"},c:1},
    {t:{sv:"Priset på de konkurrerande produkter ni valde bort",
        en:"The price of the competing products you did not buy"}}],
 e:{sv:"Inköpspriset är ofta den minsta posten. Det billigaste alternativet vid upphandling är regelbundet det dyraste sett över fem år.",
    en:"The purchase price is often the smallest item. The cheapest option at procurement is regularly the most expensive over five years."}},

{q:{sv:"När är det rimligt att bygga själv i stället för att köpa?",
    en:"When is building rather than buying reasonable?"},
 o:[{t:{sv:"När behovet är verkligt särpräglat och inget på marknaden passar",
        en:"When the need is genuinely distinctive and nothing on the market fits"},c:1},
    {t:{sv:"När lösningen är en kärnverksamhet ni vill äga",
        en:"When the solution is core business you want to own"},c:1},
    {t:{sv:"Alltid, eftersom det blir billigare", en:"Always, because it is cheaper"}},
    {t:{sv:"Sällan för standardfunktioner som autentisering",
        en:"Rarely for standard functions such as authentication"},c:1}],
 e:{sv:"Egenbyggd autentisering är ett klassiskt sätt att skapa sårbarheter som en färdig produkt redan löst. Bygg det som är er särart, köp resten.",
    en:"Home-built authentication is a classic way to create vulnerabilities a finished product already solved. Build what is distinctive to you, buy the rest."}},

{q:{sv:"Varför är acceptanskriterier viktiga i ett avtal?",
    en:"Why do acceptance criteria matter in a contract?"},
 o:[{t:{sv:"De avgör när leveransen är godkänd och betalning sker",
        en:"They decide when the delivery is approved and payment happens"},c:1},
    {t:{sv:"De gör kravet prövbart i praktiken",
        en:"They make the requirement testable in practice"},c:1},
    {t:{sv:"De behövs bara vid tvist", en:"They are only needed in a dispute"}},
    {t:{sv:"Utan dem blir «klart» en förhandling i efterhand",
        en:"Without them, 'done' becomes a negotiation after the fact"},c:1}],
 e:{sv:"Det är billigare att bråka om vad «klart» betyder innan arbetet börjar än efter att fakturan kommit.",
    en:"It is cheaper to argue about what 'done' means before the work starts than after the invoice arrives."}},

{q:{sv:"Vad bör man tänka på vid offentlig upphandling?",
    en:"What should you keep in mind in public procurement?"},
 o:[{t:{sv:"Kraven styr utfallet — det som inte efterfrågas levereras inte",
        en:"The requirements drive the outcome — what is not asked for is not delivered"},c:1},
    {t:{sv:"Likabehandling begränsar hur mycket man kan justera i efterhand",
        en:"Equal treatment limits how much can be adjusted afterwards"},c:1},
    {t:{sv:"Säkerhetskrav kan skrivas in som skallkrav",
        en:"Security requirements can be written as mandatory requirements"},c:1},
    {t:{sv:"Man kan lägga till krav efter tilldelning",
        en:"Requirements can be added after the award"}}],
 e:{sv:"Kravställningen är det enda tillfället att påverka. Säkerhet som inte står i underlaget kommer inte att finnas i leveransen.",
    en:"The requirement stage is the only chance to influence the result. Security that is not in the documents will not be in the delivery."}}]}],

etik: [
{tier:{sv:"Yrkesetik", en:"Professional ethics"}, items:[

{q:{sv:"Vad innebär ansvarsfullt röjande av sårbarheter?",
    en:"What does responsible disclosure mean?"},
 o:[{t:{sv:"Att först meddela den som kan åtgärda problemet",
        en:"Telling whoever can fix the problem first"},c:1},
    {t:{sv:"Att ge rimlig tid för åtgärd innan detaljer publiceras",
        en:"Allowing reasonable time to fix before details are published"},c:1},
    {t:{sv:"Att aldrig berätta för någon", en:"Never telling anyone"}},
    {t:{sv:"Att väga användarnas risk mot allmänhetens rätt att veta",
        en:"Weighing users' risk against the public's right to know"},c:1}],
 e:{sv:"Att publicera direkt utsätter användarna för fara; att aldrig publicera låter problemet bestå. Fastställda tidsfrister finns just för att hantera den avvägningen.",
    en:"Publishing immediately endangers users; never publishing lets the problem persist. Fixed timelines exist precisely to manage that trade-off."}},

{q:{sv:"Du hittar känsliga uppgifter under ett godkänt test. Vad gör du?",
    en:"You find sensitive data during an authorised test. What do you do?"},
 o:[{t:{sv:"Tar bara med det som behövs för att styrka fyndet",
        en:"Take only what is needed to evidence the finding"},c:1},
    {t:{sv:"Rapporterar direkt till uppdragsgivaren",
        en:"Report it to the client straight away"},c:1},
    {t:{sv:"Laddar ner allt som bevis", en:"Download everything as proof"}},
    {t:{sv:"Behandlar uppgifterna enligt samma regler som uppdragsgivaren måste följa",
        en:"Handle the data under the same rules the client must follow"},c:1}],
 e:{sv:"Mandatet att testa är inte ett mandat att samla in. En skärmbild som visar åtkomst räcker som bevis — hela databasen gör det inte bättre, bara farligare.",
    en:"A mandate to test is not a mandate to collect. A screenshot showing access is sufficient evidence — the whole database does not improve it, only endangers it."}},

{q:{sv:"Vad menas med att säkerhetskunskap är dubbelanvändbar?",
    en:"What does it mean that security knowledge is dual use?"},
 o:[{t:{sv:"Samma kunskap kan användas för att skydda och för att skada",
        en:"The same knowledge can protect and can harm"},c:1},
    {t:{sv:"Avsikt och mandat avgör vilket det blir",
        en:"Intent and mandate decide which it becomes"},c:1},
    {t:{sv:"Därför bör kunskapen hemlighållas",
        en:"Therefore the knowledge should be kept secret"}},
    {t:{sv:"Det ställer krav på omdöme, inte bara på teknik",
        en:"It places demands on judgement, not only on technique"},c:1}],
 e:{sv:"Att kunna bryta sig in är förutsättningen för att kunna försvara. Det som skiljer yrkesrollen från brottet är tillstånd, syfte och hur fyndet hanteras.",
    en:"Knowing how to break in is the precondition for defending. What separates the profession from the crime is permission, purpose and how the finding is handled."}},

{q:{sv:"När uppstår en intressekonflikt i säkerhetsarbete?",
    en:"When does a conflict of interest arise in security work?"},
 o:[{t:{sv:"När den som granskar också säljer lösningen",
        en:"When whoever assesses also sells the remedy"},c:1},
    {t:{sv:"När man granskar sitt eget arbete",
        en:"When you review your own work"},c:1},
    {t:{sv:"Aldrig, om man är kunnig", en:"Never, if you are competent"}},
    {t:{sv:"Den bör redovisas öppet snarare än döljas",
        en:"It should be declared openly rather than hidden"},c:1}],
 e:{sv:"Konflikten försvinner inte av att man är kompetent eller ärlig. Det som hanterar den är öppenhet och att någon annan granskar.",
    en:"The conflict does not disappear because you are competent or honest. What handles it is disclosure and review by someone else."}}]},

{tier:{sv:"I praktiken", en:"In practice"}, items:[

{q:{sv:"En kollega ber dig testa ett system «snabbt, utan pappersarbete». Vad gäller?",
    en:"A colleague asks you to test a system 'quickly, without the paperwork'. What applies?"},
 o:[{t:{sv:"Utan tillstånd är handlingen olaglig oavsett avsikt",
        en:"Without authorisation the act is unlawful regardless of intent"},c:1},
    {t:{sv:"Kollegan har sannolikt inte mandat att ge tillståndet",
        en:"The colleague probably lacks the authority to grant it"},c:1},
    {t:{sv:"Muntligt tillstånd räcker mellan kollegor",
        en:"Verbal permission is enough between colleagues"}},
    {t:{sv:"Det skyddar dig lika mycket som organisationen att vänta",
        en:"Waiting protects you as much as the organisation"},c:1}],
 e:{sv:"Den som ber dig hoppa över pappersarbetet står inte bredvid dig när frågan ställs efteråt. Skriftligt tillstånd är ditt skydd.",
    en:"Whoever asks you to skip the paperwork is not standing beside you when the questions come afterwards. Written authorisation is your protection."}},

{q:{sv:"Varför är tystnadsplikt central i yrkesrollen?",
    en:"Why is confidentiality central to the role?"},
 o:[{t:{sv:"Man får se system och brister som få andra får se",
        en:"You see systems and weaknesses few others are shown"},c:1},
    {t:{sv:"Ett röjt fynd kan utnyttjas innan det hunnit åtgärdas",
        en:"A disclosed finding can be exploited before it is fixed"},c:1},
    {t:{sv:"Den upphör när uppdraget avslutas",
        en:"It ends when the assignment ends"}},
    {t:{sv:"Förtroendet är förutsättningen för att få göra jobbet",
        en:"Trust is the precondition for being allowed to do the work"},c:1}],
 e:{sv:"Tystnadsplikten överlever uppdraget. Att berätta om en gammal kunds brister på en konferens är ett brott mot den, även flera år senare.",
    en:"Confidentiality outlives the assignment. Describing an old client's weaknesses at a conference breaches it, even years later."}},

{q:{sv:"Vad bör du göra om du upptäcker att din arbetsgivare bryter mot lagen?",
    en:"What should you do if you find your employer breaking the law?"},
 o:[{t:{sv:"Dokumentera det du faktiskt observerat",
        en:"Document what you actually observed"},c:1},
    {t:{sv:"Ta upp det internt först, om det är möjligt och säkert",
        en:"Raise it internally first, where that is possible and safe"},c:1},
    {t:{sv:"Ta själv bort bevisen", en:"Remove the evidence yourself"}},
    {t:{sv:"Känna till skyddet för visselblåsare innan du agerar",
        en:"Know the whistleblower protections before acting"},c:1}],
 e:{sv:"Det finns rättsligt skydd för den som slår larm, men det förutsätter att man följer en viss ordning. Att känna till den i förväg är en del av yrkesrollen.",
    en:"Legal protection exists for those who raise the alarm, but it depends on following a particular route. Knowing it in advance is part of the profession."}},

{q:{sv:"Vad utmärker en professionell rapport om ett fynd?",
    en:"What marks a professional report of a finding?"},
 o:[{t:{sv:"Den beskriver vad som observerats, inte vad som antas",
        en:"It describes what was observed, not what is assumed"},c:1},
    {t:{sv:"Den skiljer på fakta och bedömning",
        en:"It separates fact from judgement"},c:1},
    {t:{sv:"Den överdriver allvaret för att få gehör",
        en:"It overstates severity to get attention"}},
    {t:{sv:"Den är läsbar för dem som ska fatta beslut",
        en:"It is readable by the people who must decide"},c:1}],
 e:{sv:"Överdrift fungerar en gång. Därefter viktas allt du säger ner, inklusive det som verkligen är allvarligt.",
    en:"Overstatement works once. After that everything you say gets discounted, including the things that really are serious."}}]}],

juridik: [
{tier:{sv:"Dataskydd", en:"Data protection"}, items:[

{q:{sv:"Vilka är några av GDPR:s grundläggande principer?",
    en:"What are some of the GDPR's core principles?"},
 o:[{t:{sv:"Ändamålsbegränsning — uppgifter samlas in för angivna ändamål",
        en:"Purpose limitation — data is collected for stated purposes"},c:1},
    {t:{sv:"Uppgiftsminimering — inte mer än vad som behövs",
        en:"Data minimisation — no more than is needed"},c:1},
    {t:{sv:"Lagringsminimering — inte längre än nödvändigt",
        en:"Storage limitation — no longer than necessary"},c:1},
    {t:{sv:"Att all behandling kräver samtycke",
        en:"That all processing requires consent"}}],
 e:{sv:"Samtycke är bara en av flera rättsliga grunder, och ofta den svagaste eftersom det kan återkallas. Avtal och rättslig förpliktelse är vanligare i praktiken.",
    en:"Consent is only one lawful basis, and often the weakest since it can be withdrawn. Contract and legal obligation are more common in practice."}},

{q:{sv:"Vad skiljer personuppgiftsansvarig från personuppgiftsbiträde?",
    en:"What separates a controller from a processor?"},
 o:[{t:{sv:"Den ansvarige bestämmer ändamål och medel för behandlingen",
        en:"The controller decides the purposes and means of processing"},c:1},
    {t:{sv:"Biträdet behandlar uppgifter för den ansvariges räkning",
        en:"The processor handles data on the controller's behalf"},c:1},
    {t:{sv:"Molnleverantörer är typiskt biträden",
        en:"Cloud providers are typically processors"},c:1},
    {t:{sv:"Rollerna är utbytbara", en:"The roles are interchangeable"}}],
 e:{sv:"Rollen avgör ansvaret, och den följer av vem som faktiskt bestämmer — inte av vad parterna kallar sig i avtalet.",
    en:"The role decides the responsibility, and it follows from who actually decides — not from what the parties call themselves in the contract."}},

{q:{sv:"Vad gäller vid en personuppgiftsincident?",
    en:"What applies when there is a personal data breach?"},
 o:[{t:{sv:"Anmälan till tillsynsmyndigheten inom 72 timmar, om risk föreligger",
        en:"Notification to the supervisory authority within 72 hours, where there is risk"},c:1},
    {t:{sv:"De registrerade ska informeras vid hög risk",
        en:"Data subjects must be told where the risk is high"},c:1},
    {t:{sv:"Man behöver bara anmäla om uppgifterna faktiskt missbrukats",
        en:"You only report if the data was actually misused"}},
    {t:{sv:"Incidenten ska dokumenteras även om den inte anmäls",
        en:"The incident must be documented even when not reported"},c:1}],
 e:{sv:"Klockan startar när ni fått kännedom, inte när utredningen är klar. Därför är förberedda rutiner viktigare än snabbhet i stunden.",
    en:"The clock starts when you become aware, not when the investigation finishes. That is why prepared procedure matters more than speed in the moment."}},

{q:{sv:"När krävs en konsekvensbedömning (DPIA)?",
    en:"When is a data protection impact assessment required?"},
 o:[{t:{sv:"När behandlingen sannolikt medför hög risk för de registrerade",
        en:"When the processing is likely to be high risk for the individuals"},c:1},
    {t:{sv:"Vid systematisk och omfattande kartläggning av personer",
        en:"For systematic and extensive profiling of people"},c:1},
    {t:{sv:"Vid all behandling av personuppgifter",
        en:"For all processing of personal data"}},
    {t:{sv:"Vid storskalig behandling av känsliga uppgifter",
        en:"For large-scale processing of sensitive data"},c:1}],
 e:{sv:"Bedömningen ska göras innan behandlingen börjar. Gjord efteråt är den en efterhandskonstruktion, inte ett beslutsunderlag.",
    en:"The assessment must be done before the processing starts. Done afterwards it is a rationalisation, not a basis for a decision."}}]},

{tier:{sv:"Övrig reglering", en:"Other regulation"}, items:[

{q:{sv:"Vad innebär NIS2 i korthet?",
    en:"What does NIS2 mean, in short?"},
 o:[{t:{sv:"Krav på säkerhetsåtgärder för verksamheter i utpekade samhällsviktiga sektorer",
        en:"Security requirements for organisations in designated essential sectors"},c:1},
    {t:{sv:"Skyldighet att rapportera allvarliga incidenter",
        en:"An obligation to report significant incidents"},c:1},
    {t:{sv:"Ansvar som uttryckligen ligger på ledningen",
        en:"Responsibility that rests explicitly with management"},c:1},
    {t:{sv:"Att det ersätter GDPR", en:"That it replaces the GDPR"}}],
 e:{sv:"NIS2 handlar om driftsäkerhet i samhällsviktig verksamhet, GDPR om skydd av personuppgifter. De gäller parallellt och överlappar delvis.",
    en:"NIS2 concerns operational resilience in essential services; the GDPR concerns protection of personal data. They apply in parallel and partly overlap."}},

{q:{sv:"Varför kan loggning stå i konflikt med dataskydd?",
    en:"Why can logging conflict with data protection?"},
 o:[{t:{sv:"Loggar innehåller ofta personuppgifter",
        en:"Logs often contain personal data"},c:1},
    {t:{sv:"De behöver ändamål, gallringstid och åtkomstbegränsning som allt annat",
        en:"They need a purpose, a retention period and access control like anything else"},c:1},
    {t:{sv:"Loggar är undantagna från dataskyddsregler",
        en:"Logs are exempt from data protection rules"}},
    {t:{sv:"«Vi sparar allt för alltid» är svårt att motivera",
        en:"'We keep everything forever' is hard to justify"},c:1}],
 e:{sv:"Säkerhet är ett legitimt ändamål för loggning, men det motiverar inte obegränsad lagring eller att vem som helst får läsa.",
    en:"Security is a legitimate purpose for logging, but it does not justify unlimited retention or letting anyone read them."}},

{q:{sv:"Vad bör man tänka på vid överföring av personuppgifter till tredje land?",
    en:"What should you consider when transferring personal data outside the EU?"},
 o:[{t:{sv:"Det krävs en rättslig grund för själva överföringen",
        en:"A legal basis is required for the transfer itself"},c:1},
    {t:{sv:"Var data faktiskt lagras och vem som kan begära åtkomst",
        en:"Where the data actually sits and who can demand access to it"},c:1},
    {t:{sv:"Att en molntjänst med europeisk region alltid är tillräckligt",
        en:"That a cloud region inside Europe is always sufficient"}},
    {t:{sv:"Att underleverantörer kan innebära överföringar ni inte känner till",
        en:"That subprocessors can create transfers you do not know about"},c:1}],
 e:{sv:"Regionvalet avgör var data ligger, men inte nödvändigtvis vem som rättsligt kan begära ut den. Ägarförhållanden och underleverantörer spelar roll.",
    en:"The region setting decides where data sits, but not necessarily who can lawfully demand it. Ownership and subprocessors matter."}},

{q:{sv:"Varför är efterlevnad inte samma sak som säkerhet?",
    en:"Why is compliance not the same as security?"},
 o:[{t:{sv:"Regler anger en lägstanivå, inte en tillräcklig nivå",
        en:"Regulation sets a floor, not a sufficient level"},c:1},
    {t:{sv:"Man kan uppfylla varje krav och ändå bli komprometterad",
        en:"You can meet every requirement and still be compromised"},c:1},
    {t:{sv:"Efterlevnad är meningslös", en:"Compliance is pointless"}},
    {t:{sv:"Kraven släpar efter hotutvecklingen",
        en:"Requirements lag behind how threats develop"},c:1}],
 e:{sv:"Efterlevnad är värdefull — den tvingar fram grundläggande ordning. Felet är att betrakta den som mål i stället för golv.",
    en:"Compliance is valuable — it forces basic order. The mistake is treating it as the goal rather than the floor."}}]}]

};
